-- Build Your Health remake schema (RQ-F-001).
-- Column names are fixed: the integration tests depend on them.
-- Only the primary keys are indexed. Oracle does not index foreign key columns
-- automatically, and that is intentional here: index design is the next milestone
-- (R2), which measures execution plans and response times before and after.

CREATE TABLE MEMBER (
    ID            VARCHAR2(50 CHAR)  NOT NULL,
    PASSWORD_HASH VARCHAR2(100 CHAR) NOT NULL,
    NAME          VARCHAR2(100 CHAR) NOT NULL,
    REG_DATE      TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_MEMBER PRIMARY KEY (ID)
);

CREATE TABLE PRODUCT (
    PRODUCT_ID      VARCHAR2(10 CHAR)  NOT NULL,
    PRODUCT_NAME    VARCHAR2(100 CHAR) NOT NULL,
    REGULAR_PRICE   NUMBER(10),
    DISCOUNT_PRICE  NUMBER(10)         NOT NULL,
    MANUFACTURER    VARCHAR2(50 CHAR),
    SHIPPING_INFO   VARCHAR2(50 CHAR),
    IMAGE_FILE      VARCHAR2(100 CHAR),
    PRODUCT_OPTIONS CLOB,
    ARRIVAL_DATE    DATE,
    CONSTRAINT PK_PRODUCT PRIMARY KEY (PRODUCT_ID)
);

CREATE TABLE ORDERS (
    ORDER_ID         NUMBER GENERATED ALWAYS AS IDENTITY,
    USER_ID          VARCHAR2(50 CHAR)  NOT NULL,
    ORDER_DATE       TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    DELIVERY_DATE    DATE               NOT NULL,
    TOTAL_PRICE      NUMBER(12)         NOT NULL,
    RECIPIENT_NAME   VARCHAR2(100 CHAR) NOT NULL,
    SHIPPING_ADDRESS VARCHAR2(255 CHAR) NOT NULL,
    SHIPPING_ZIPCODE VARCHAR2(20 CHAR),
    CONSTRAINT PK_ORDERS PRIMARY KEY (ORDER_ID),
    CONSTRAINT FK_ORDERS_MEMBER FOREIGN KEY (USER_ID) REFERENCES MEMBER (ID) ON DELETE CASCADE
);

CREATE TABLE ORDER_ITEMS (
    ITEM_ID    NUMBER GENERATED ALWAYS AS IDENTITY,
    ORDER_ID   NUMBER            NOT NULL,
    PRODUCT_ID VARCHAR2(10 CHAR) NOT NULL,
    QUANTITY   NUMBER(9)         NOT NULL,
    PRICE      NUMBER(10)        NOT NULL,
    CONSTRAINT PK_ORDER_ITEMS PRIMARY KEY (ITEM_ID),
    CONSTRAINT FK_ORDER_ITEMS_ORDERS FOREIGN KEY (ORDER_ID) REFERENCES ORDERS (ORDER_ID) ON DELETE CASCADE,
    CONSTRAINT FK_ORDER_ITEMS_PRODUCT FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT (PRODUCT_ID) ON DELETE CASCADE
);
