#requires -Version 7.0
[CmdletBinding()]
param([ValidateSet(5,10,20)][int]$Tps=10, [ValidateRange(1,2)][int]$Repeat=1, [string]$Label='baseline', [int]$Seconds=120)
$ErrorActionPreference='Stop'
$PSNativeCommandUseErrorActionPreference=$true
if ($Label -notmatch '^[a-z0-9-]+$') { throw 'Invalid result label' }
if ($Seconds -lt 120) { throw 'Measured duration must be at least 120s' }
$out=Join-Path $PSScriptRoot "results/$Label-$Tps-r$Repeat"
if (Test-Path $out) { throw "Result already exists: $out" }
New-Item -ItemType Directory $out | Out-Null
function Invoke-SqlFile([string]$File) {
    Get-Content -Raw (Join-Path $PSScriptRoot $File) | docker --context desktop-linux exec -i byh-perf-perfdb-1 sqlplus -s / as sysdba
}
$rows=Invoke-SqlFile 'snapshot.sql'
if (($rows -join '') -notmatch 'ROWS\|22021\|2001\|600000\|1499546') { throw 'Initial fixed seed counts do not match; inspect prior run cleanup' }
$rows | Set-Content (Join-Path $out 'db-before.txt')
$appId='byh-loadtest-app-1'
$k6Image='grafana/k6@sha256:e66db15b860113878fa74670e31f5e274830b7b6e42c8bff28b2f2d86a257603'
$jdkImage='eclipse-temurin@sha256:5d6042fb8cdc14d614e4e421f52e3211fc5aeadddce44cbf9de8ed37c791f824'
# Run observer in a separate container, no published JMX port.
docker --context desktop-linux create --name "byh-jmx-$Label-$Tps-r$Repeat" --network byh-perf_default $jdkImage java /JmxProbe.java ($Seconds+65) | Set-Content (Join-Path $out 'observer-id.txt')
docker --context desktop-linux cp (Join-Path $PSScriptRoot 'JmxProbe.java') "byh-jmx-$Label-$Tps-r${Repeat}:/JmxProbe.java"
docker --context desktop-linux start "byh-jmx-$Label-$Tps-r$Repeat" | Out-Null
docker --context desktop-linux create --user 0 --name "byh-k6-$Label-$Tps-r$Repeat" --network byh-perf_default -e "TPS=$Tps" -e "SECONDS=$Seconds" $k6Image run --out json=/out/raw.json.gz /mixed.js | Set-Content (Join-Path $out 'k6-id.txt')
docker --context desktop-linux cp (Join-Path $PSScriptRoot 'mixed.js') "byh-k6-$Label-$Tps-r${Repeat}:/mixed.js"
docker --context desktop-linux cp $out "byh-k6-$Label-$Tps-r${Repeat}:/out"
$k6Args=@('--context','desktop-linux','start','-a',"byh-k6-$Label-$Tps-r$Repeat")
# Poll process every 5s while saving Docker CPU/memory evidence.
$k6Log=Join-Path $out 'k6.txt'
$k6Err=Join-Path $out 'k6-stderr.txt'
$process=Start-Process docker -ArgumentList ($k6Args | ForEach-Object { '"'+$_+'"' }) -PassThru -WindowStyle Hidden -RedirectStandardOutput $k6Log -RedirectStandardError $k6Err
try {
    while (-not $process.HasExited) {
        [DateTime]::UtcNow.ToString('o') | Add-Content (Join-Path $out 'docker-stats.txt')
        # The k6 container may still be starting on the first poll.
        $PSNativeCommandUseErrorActionPreference=$false
        docker --context desktop-linux stats --no-stream --format '{{json .}}' $appId byh-perf-perfdb-1 "byh-k6-$Label-$Tps-r$Repeat" 2>&1 | Add-Content (Join-Path $out 'docker-stats.txt')
        $PSNativeCommandUseErrorActionPreference=$true
        Start-Sleep -Seconds 3
        $process.Refresh()
    }
    $process.WaitForExit()
    $process.ExitCode | Set-Content (Join-Path $out 'exit-code.txt')
    docker --context desktop-linux cp "byh-k6-$Label-$Tps-r${Repeat}:/out/summary.json" (Join-Path $out 'summary.json')
    docker --context desktop-linux cp "byh-k6-$Label-$Tps-r${Repeat}:/out/raw.json.gz" (Join-Path $out 'raw.json.gz')
    Invoke-SqlFile 'snapshot.sql' | Set-Content (Join-Path $out 'db-after.txt')
    Invoke-SqlFile 'plans.sql' | Set-Content (Join-Path $out 'plans.txt')
    if (-not (Test-Path (Join-Path $out 'plans.txt'))) { throw 'Oracle cursor plan output is missing' }
    docker --context desktop-linux logs "byh-jmx-$Label-$Tps-r$Repeat" 2>&1 | Set-Content (Join-Path $out 'hikari.csv')
    docker --context desktop-linux logs $appId 2>&1 | Set-Content (Join-Path $out 'app.txt')
    if (-not (Test-Path (Join-Path $out 'summary.json'))) { throw 'k6 produced no summary; result is incomplete' }
} finally {
    docker --context desktop-linux rm -f "byh-k6-$Label-$Tps-r$Repeat" | Out-Null
    # Remove only orders generated by this harness in the isolated clone.
    @'
whenever sqlerror exit failure rollback
alter session set container=FREEPDB1;
delete from byh_load.order_items where order_id in (select order_id from byh_load.orders where recipient_name='K6_LOAD_TEST' and order_id>600000);
delete from byh_load.orders where recipient_name='K6_LOAD_TEST' and order_id>600000;
commit;
exit;
'@ | docker --context desktop-linux exec -i byh-perf-perfdb-1 sqlplus -s / as sysdba | Set-Content (Join-Path $out 'cleanup.txt')
    Invoke-SqlFile 'snapshot.sql' | Set-Content (Join-Path $out 'db-clean.txt')
    Invoke-SqlFile 'checksum.sql' | Set-Content (Join-Path $out 'seed-checksums.txt')
    docker --context desktop-linux rm -f "byh-jmx-$Label-$Tps-r$Repeat" | Out-Null
}
$summary=Get-Content -Raw (Join-Path $out 'summary.json') | ConvertFrom-Json
$summary.metrics.measured_latency.values | Format-List
$summary.metrics.measured_requests.values | Format-List
$summary.metrics.measured_errors.values | Format-List
Write-Output "RESULT=$out K6_EXIT=$($process.ExitCode)"
